services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres        
      POSTGRES_PASSWORD: password   
      POSTGRES_DB: newsletter        
    ports:
      - "5432:5432"                 
    command: ["-N", "1000"]          # Increase max client connections
    volumes:
      - postgres_data:/var/lib/postgresql/data
        #- ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 1s                   # Time between checks
      timeout: 5s                    # Timeout for each check
      retries: 5                     # Fail after 5 unsuccessful attempts
    networks:
        - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "8080:80"
    networks:
        - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres_data: # Named volume for data persistence

